### PR TITLE
handling some AttributeErrors

### PR DESCRIPTION
**Pull request by derekeder**
Handles the following sentry errors:

* https://datamade.sentry.io/issues/4820142834/?project=63977
* https://datamade.sentry.io/issues/4505824150/?project=63977

### CODE REVIEW

**Comment by fgregg** [comment]
hmm.. these seem like times when those objects should always have those attributes?

**Comment by derekeder** [comment]
yes, I agree. we should handle this on the data side as well. i think these fixes are worth including as they currently are breaking the `rss` feed and some committee pages

**Comment by fgregg** [comment]
that makes sense, let's have the errors be sent to sentry then in the condition that the attributes are missing.

**Comment by derekeder** [comment]
ok i'll make that change

**Review by fgregg — APPROVED** [review]

**Pull request merged**
